<a href="https://colab.research.google.com/github/AdityaHegde23/PyTorch-exercises/blob/main/00_pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pytorch basics and exercises

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
TENSOR = torch.tensor([[[1,2,3],[1,3,4],[56,55,6]],[[66,55,1],[77,78,1],[99,88,1]]])

In [ ]:
TENSOR


tensor([[[ 1,  2,  3],
         [ 1,  3,  4],
         [56, 55,  6]],

        [[66, 55,  1],
         [77, 78,  1],
         [99, 88,  1]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#Create random tensor
random_tensor = torch.rand(3,4,8)

In [ ]:
random_tensor

tensor([[[0.0929, 0.4367, 0.7227, 0.1688, 0.1327, 0.6506, 0.2141, 0.2330],
         [0.4011, 0.7960, 0.7347, 0.1921, 0.4164, 0.3244, 0.9308, 0.1086],
         [0.5008, 0.5934, 0.9556, 0.4483, 0.1065, 0.8872, 0.7527, 0.5986],
         [0.1388, 0.2990, 0.8511, 0.5139, 0.6783, 0.4601, 0.2514, 0.1213]],

        [[0.1267, 0.6756, 0.1251, 0.6950, 0.7494, 0.7390, 0.2515, 0.0562],
         [0.0237, 0.9210, 0.4610, 0.6752, 0.7801, 0.0195, 0.5913, 0.3533],
         [0.1185, 0.6195, 0.3430, 0.3073, 0.7691, 0.4196, 0.6211, 0.6455],
         [0.9770, 0.5565, 0.3358, 0.7824, 0.4223, 0.3408, 0.5755, 0.1750]],

        [[0.4741, 0.0735, 0.1680, 0.6481, 0.3766, 0.0363, 0.4118, 0.0940],
         [0.8347, 0.7616, 0.7525, 0.7530, 0.2433, 0.9555, 0.6144, 0.4612],
         [0.3004, 0.8808, 0.6838, 0.0946, 0.3144, 0.0931, 0.5988, 0.6101],
         [0.4108, 0.1618, 0.8664, 0.6293, 0.5405, 0.0924, 0.1970, 0.5098]]])

In [ ]:
 x = torch.rand(3,7,8)

In [ ]:
x.max()

tensor(0.9968)

In [ ]:
#regular element level multiplication
y = x*x

In [ ]:
y.shape

torch.Size([3, 7, 8])

In [ ]:
#Matrix transpose
x.T

tensor([[[0.5314, 0.9082, 0.6110],
         [0.9043, 0.8740, 0.8277],
         [0.4061, 0.1403, 0.1518],
         [0.4064, 0.6678, 0.6721],
         [0.9444, 0.6352, 0.1678],
         [0.3833, 0.7627, 0.3975],
         [0.7796, 0.3170, 0.8924]],

        [[0.5177, 0.8814, 0.1200],
         [0.7271, 0.3272, 0.1799],
         [0.5862, 0.4114, 0.1465],
         [0.3745, 0.9867, 0.4565],
         [0.1970, 0.3410, 0.9163],
         [0.0757, 0.9499, 0.4441],
         [0.5917, 0.3360, 0.9968]],

        [[0.8932, 0.6084, 0.1426],
         [0.9576, 0.7479, 0.5305],
         [0.8348, 0.7342, 0.5542],
         [0.9333, 0.0274, 0.5859],
         [0.4436, 0.1431, 0.9518],
         [0.4386, 0.1916, 0.5650],
         [0.0065, 0.0063, 0.4900]],

        [[0.8857, 0.1232, 0.6564],
         [0.1233, 0.1005, 0.2733],
         [0.7461, 0.2673, 0.4829],
         [0.4732, 0.7885, 0.7588],
         [0.5813, 0.7200, 0.8132],
         [0.8198, 0.8177, 0.3869],
         [0.6358, 0.5810, 0.4508]],

        [[0.

In [ ]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
x.unsqueeze(0)

tensor([[[[0.5314, 0.5177, 0.8932, 0.8857, 0.3309, 0.0173, 0.5881, 0.1412],
          [0.9043, 0.7271, 0.9576, 0.1233, 0.4344, 0.0050, 0.7881, 0.8449],
          [0.4061, 0.5862, 0.8348, 0.7461, 0.8395, 0.3520, 0.9024, 0.2238],
          [0.4064, 0.3745, 0.9333, 0.4732, 0.7664, 0.8800, 0.8077, 0.6052],
          [0.9444, 0.1970, 0.4436, 0.5813, 0.1987, 0.9589, 0.2947, 0.7369],
          [0.3833, 0.0757, 0.4386, 0.8198, 0.3582, 0.0919, 0.9377, 0.0760],
          [0.7796, 0.5917, 0.0065, 0.6358, 0.2739, 0.0105, 0.6152, 0.1990]],

         [[0.9082, 0.8814, 0.6084, 0.1232, 0.9288, 0.5986, 0.5599, 0.2091],
          [0.8740, 0.3272, 0.7479, 0.1005, 0.3674, 0.3584, 0.5945, 0.7126],
          [0.1403, 0.4114, 0.7342, 0.2673, 0.0106, 0.2156, 0.7530, 0.7986],
          [0.6678, 0.9867, 0.0274, 0.7885, 0.3838, 0.5418, 0.3052, 0.7990],
          [0.6352, 0.3410, 0.1431, 0.7200, 0.5793, 0.5606, 0.7746, 0.7345],
          [0.7627, 0.9499, 0.1916, 0.8177, 0.3716, 0.4012, 0.0851, 0.4092],
          

In [ ]:
x_image = torch.rand(244,244,3)

In [ ]:
x_image

tensor([[[0.8557, 0.3758, 0.2179],
         [0.5274, 0.2780, 0.7369],
         [0.4629, 0.9218, 0.6378],
         ...,
         [0.8801, 0.3308, 0.5894],
         [0.5088, 0.8423, 0.8581],
         [0.7713, 0.2837, 0.2681]],

        [[0.8302, 0.4706, 0.0545],
         [0.3986, 0.2132, 0.3482],
         [0.0509, 0.7071, 0.1385],
         ...,
         [0.8447, 0.0699, 0.4913],
         [0.5898, 0.7101, 0.5046],
         [0.3934, 0.2978, 0.2233]],

        [[0.6152, 0.5668, 0.0836],
         [0.3483, 0.2802, 0.4892],
         [0.6346, 0.9758, 0.4063],
         ...,
         [0.1140, 0.6073, 0.0197],
         [0.0147, 0.5978, 0.2544],
         [0.4094, 0.5804, 0.6135]],

        ...,

        [[0.7511, 0.5383, 0.4777],
         [0.7290, 0.6237, 0.0367],
         [0.6397, 0.0209, 0.1597],
         ...,
         [0.6922, 0.7755, 0.3118],
         [0.2527, 0.3727, 0.3150],
         [0.8413, 0.5279, 0.2046]],

        [[0.6585, 0.1424, 0.9772],
         [0.9027, 0.6765, 0.9137],
         [0.

fatal: not a git repository (or any of the parent directories): .git
